Update .zprofile

diff --git a/dot_zprofile b/dot_zprofile
--- a/dot_zprofile
+++ b/dot_zprofile
@@ -1,7 +1,26 @@
-if [[ "$(tty)" == "/dev/tty1" ]]
- then
-  sh .local/share/bin/hyprland.sh && echo "goodbye, now logging out" && exit 0 \
-   || echo "$? hyperland.sh failed" && tty |grep tty1 \
-    && echo "refusing autologin without hyprland on tty1" && exit 0 \
-    || echo "not on tty1, proceeding..."
+# Start Hyprland if on TTY1
+if [[ "$(tty)" == "/dev/tty1" ]]; then
+    export USER=s
+    [ -z $TERM ] && export TERM=linux
+    [ -z $LOGNAME ] && export LOGNAME=$USER
+    [ -z $HOME ] && export HOME=/home/$USER
+    [ -z $LANG ] && export LANG=C.UTF-8
+    [ -z $PATH ] && export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
+    [ -z $XDG_SEAT ] && export XDG_SEAT=seat0
+    [ -z $XDG_SESSION_TYPE ]  && export XDG_SESSION_TYPE=tty
+    [ -z $XDG_SESSION_CLASS ] && export XDG_SESSION_CLASS=user
+    [ -z $XDG_VTNR ] && export XDG_VTNR=1
+    [ -z $XDG_RUNTIME_DIR ] && export XDG_RUNTIME_DIR=/run/user/1000
+    [ -z $DBUS_SESSION_BUS_ADDRESS ] && export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
+    export HYPRLAND_LOG_WLR=1
+    exec Hyprland > hyprland.log
+else
+    echo "refusing autologin without hyprland on tty1" && exit -1 > hyprfail.log
 fi
+# if [[ "$(tty)" == "/dev/tty1" ]]
+#  then
+#   sh .local/share/bin/hyprland.sh && echo "goodbye, now logging out" && exit 0 \
+#    || echo "$? hyperland.sh failed" && tty |grep tty1 \
+#     && echo "refusing autologin without hyprland on tty1" && exit 0 \
+#     || echo "not on tty1, proceeding..."
+# fi
